# Generated by Django 2.1.7 on 2019-05-07 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogFound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('founder_name', models.CharField(max_length=255)),
                ('founder_info', models.TextField()),
                ('founder_phone', models.CharField(max_length=20)),
                ('dog_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('dog_image', models.ImageField(default='default-dog.jpg', upload_to='dog_img')),
                ('dog_breed', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Breed')),
                ('dog_color', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.DogColor')),
            ],
        ),
    ]
