# Generated by Django 2.1.7 on 2019-05-03 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190502_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='owner',
            name='staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='owner',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
