# Generated by Django 2.1.7 on 2019-05-04 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20190504_0329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='user',
        ),

    ]
