# Generated by Django 2.1.7 on 2019-05-03 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190503_0020'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
