# Generated by Django 2.1.7 on 2019-05-05 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190504_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=30)),

            ],
        ),
        migrations.AlterField(
            model_name='dog',
            name='dog_info',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='qr_code',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='dogcolor',
            name='dog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Dog'),
        ),
    ]
