# Generated by Django 2.1.7 on 2019-05-04 05:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_ownerprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OwnerProfile',
            new_name='Profile',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='user',
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
