# Generated by Django 2.1.7 on 2019-05-03 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_delete_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_status', models.CharField(choices=[('Death', 'Death'), ('Normal', 'Normal'), ('Lost', 'Lost')], default='Normal', max_length=20)),
                ('dog_name', models.CharField(max_length=50)),
                ('dog_info', models.TextField()),
                ('dog_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('dog_dob', models.DateField(blank=True, null=True)),
                ('dog_age', models.IntegerField(default=0)),
                ('qr_code', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_phone', models.CharField(max_length=15)),
                ('owner_address', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dog',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Owner'),
        ),
    ]
