# Generated by Django 2.1.7 on 2019-05-05 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190505_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='dog_image',
            field=models.ImageField(default='default.jpg', upload_to='dog_img'),
        ),
    ]
