# Generated by Django 2.1.7 on 2019-05-05 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190505_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='breed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Breed'),
        ),
    ]
