# Generated by Django 2.1.7 on 2019-05-06 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190505_0507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogcolor',
            name='dog',
        ),
        migrations.AddField(
            model_name='dog',
            name='dog_breed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Breed'),
        ),
    ]
