# Generated by Django 2.1.7 on 2019-05-06 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190506_1857'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DogColor',
        ),

    ]
