# Generated by Django 2.1.7 on 2019-05-06 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20190506_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='color1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.DogColor'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='dog_image',
            field=models.ImageField(default='default-dog.jpg', upload_to='dog_img'),
        ),
    ]
