# Generated by Django 2.2.1 on 2019-05-23 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_title', models.CharField(max_length=100)),
                ('post_detail', models.TextField()),
                ('post_status', models.CharField(choices=[('0', '0'), ('1', '1')], max_length=2)),
                ('latitude', models.FloatField()),
                ('longtitude', models.FloatField()),
                ('types', models.CharField(choices=[('0', '0'), ('1', '1')], max_length=2)),
                ('dog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Dog')),
                ('founder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.DogFound')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
