# Generated by Django 2.1.7 on 2019-05-07 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_dogfound'),
        ('newfeeds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='founder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.DogFound'),
        ),
        migrations.AlterField(
            model_name='post',
            name='dog',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Dog'),
        ),
        migrations.AlterField(
            model_name='post',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
