# Generated by Django 2.1.7 on 2019-05-03 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newfeeds', '0002_auto_20190502_0720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('post_title', models.CharField(max_length=100)),
                ('post_detail', models.TextField()),
                ('post_status', models.CharField(choices=[(0, 0), (1, 1)], max_length=2)),
                ('latitude', models.FloatField()),
                ('longtitude', models.FloatField()),
                ('types', models.CharField(choices=[(0, 0), (1, 1)], max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
