# Generated by Django 2.2.1 on 2019-05-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newfeeds', '0002_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='latitude',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='longitude',
            field=models.CharField(max_length=50),
        ),
    ]
