# Generated by Django 2.1.7 on 2019-05-03 00:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newfeeds', '0003_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
