# Generated by Django 2.2.1 on 2019-05-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newfeeds', '0003_auto_20190524_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
