# Generated by Django 2.1.7 on 2019-05-04 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newfeeds', '0004_auto_20190503_0054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_time',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='ower',
        ),
    ]
