# Generated by Django 2.1.7 on 2019-05-05 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newfeeds', '0005_auto_20190504_0251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='ower',
            new_name='owner',
        ),
    ]
