# Generated by Django 2.1.7 on 2019-05-06 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newfeeds', '0007_auto_20190506_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Dog'),
        ),
    ]
